### ISSUE TITLE
Missing libthai on AppImage 0.5.1

### ISSUE THREAD

**Issue by bombonatti** [phil294/AHK_X11#45]
First time I tried to run, I got dependency issue.

bash-5.2$ ./ahk_x11-0.5.1-x86_64.AppImage --windowspy
/tmp/.mount_ahk_x12CnB3E/AppRun.wrapped: error while loading shared libraries: libthai.so.0: cannot open shared object file: No such file or directory

After installing libthai, works as expected.

bash-5.2$ ./ahk_x11-0.5.1-x86_64.AppImage --windowspy
Interactive AHK_X11 console (REPL). Type any command. Multi-line text not supported. Press {CTRL}+C to exit.
ahk_x11>

**Comment by phil294** [comment]
which linux / distribution / version are you using?

**Comment by bombonatti** [comment]
> which linux / distribution / version are you using?

I am using Slackware 15.0 x86_64 (post 15.0 -current) .

**Comment by phil294** [comment]
fixed with 0.6.0

**Comment by bombonatti** [comment]
Just tested and issue is not fixed (version 0.5.2 on 0.6.0 assets)

ash-5.2$ ./ahk_x11-0.5.2-x86_64.AppImage --windowspy
/tmp/.mount_ahk_x1NjgM5y/AppRun.wrapped: error while loading shared libraries: libthai.so.0: cannot open shared object file: No such file or directory

After installing libthai 0.1.28:

bash-5.2$ ./ahk_x11-0.5.2-x86_64.AppImage --windowspy
Interactive AHK_X11 console (REPL). Type any command. Multi-line text not supported. Press {CTRL}+C to exit.
ahk_x11>

**Comment by phil294** [comment]
sorry, you're right - I both hadn't fixed the missing library and the release binary version number was wrong. But all should be fixed now, could you kindly test it again?

**Comment by bombonatti** [comment]
Thank you for your reply, but it is not fixed yet.

bash-5.2$ ./ahk_x11-1.0.0-x86_64.AppImage --windowspy
/tmp/.mount_ahk_x11zz8PW/AppRun.wrapped: error while loading shared libraries: libthai.so.0: cannot open shared object file: No such file or directory

After installing libthai 0.1.28:

bash-5.2$ ./ahk_x11-1.0.0-x86_64.AppImage --windowspy
Interactive AHK_X11 console (REPL). Type any command. Multi-line text not supported. Press {CTRL}+C to exit.
ahk_x11>

**Comment by phil294** [comment]
Argh. How do I get this wrong again and again. But now it's fixed at least (it has to be!!!)

**Comment by Korne127** [comment]
The `--library /lib/x86_64-linux-gnu/libthai.so.0` can be removed again as https://github.com/AppImageCommunity/pkg2appimage/pull/555 fixes this in `linuxdeploy`.
